// Row shape is hand-written until src/api/types.gen.ts exists (generated by
// `npx supabase gen types typescript --local`). It mirrors public.profiles in
// supabase/migrations/20260916120000_messenger_core.sql exactly.

import { supabase } from '@/api/supabase';

type ProfileRow = {
  id: string;
  username: string | null;
  display_name: string | null;
  avatar_url: string | null;
  bio: string | null;
};

export type Profile = {
  id: string;
  /** Null until the user picks one — the trigger that creates the row leaves it empty. */
  username: string | null;
  /** Null when the OAuth provider sent no name. */
  displayName: string | null;
  avatarUrl: string | null;
  bio: string | null;
};

export type ProfileUpdateInput = Partial<
  Pick<Profile, 'username' | 'displayName' | 'avatarUrl' | 'bio'>
>;

/** Thrown when the unique index on profiles.username rejects the update. */
export class UsernameTakenError extends Error {
  constructor(username: string) {
    super(`Username "${username}" is already taken`);
    this.name = 'UsernameTakenError';
  }
}

export class NotAuthenticatedError extends Error {
  constructor() {
    super('No active session');
    this.name = 'NotAuthenticatedError';
  }
}

const COLUMNS = 'id, username, display_name, avatar_url, bio';

function toProfile(row: ProfileRow): Profile {
  return {
    id: row.id,
    username: row.username,
    displayName: row.display_name,
    avatarUrl: row.avatar_url,
    bio: row.bio,
  };
}

async function requireUserId(): Promise<string> {
  const { data, error } = await supabase.auth.getSession();

  if (error) {
    throw error;
  }

  const userId = data.session?.user.id;

  if (!userId) {
    throw new NotAuthenticatedError();
  }

  return userId;
}

export async function getProfile(userId: string): Promise<Profile> {
  const { data, error } = await supabase
    .from('profiles')
    .select(COLUMNS)
    .eq('id', userId)
    .is('deleted_at', null)
    .single<ProfileRow>();

  if (error) {
    throw error;
  }

  return toProfile(data);
}

export async function getMyProfile(): Promise<Profile> {
  return getProfile(await requireUserId());
}

export async function updateMyProfile(input: ProfileUpdateInput): Promise<Profile> {
  const userId = await requireUserId();

  const patch: Record<string, string | null> = {};

  if ('username' in input) {
    patch.username = input.username ?? null;
  }
  if ('displayName' in input) {
    patch.display_name = input.displayName ?? null;
  }
  if ('avatarUrl' in input) {
    patch.avatar_url = input.avatarUrl ?? null;
  }
  if ('bio' in input) {
    patch.bio = input.bio ?? null;
  }

  const { data, error } = await supabase
    .from('profiles')
    .update(patch)
    .eq('id', userId)
    .select(COLUMNS)
    .single<ProfileRow>();

  if (error) {
    // 23505 is Postgres unique_violation; profiles_username_key is the only
    // unique index on this table, so the collision can only be the username.
    if (error.code === '23505' && typeof patch.username === 'string') {
      throw new UsernameTakenError(patch.username);
    }

    throw error;
  }

  return toProfile(data);
}
