plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.openger.app'
version = '1.0.0'

android {
  namespace "expo.modules.callservice"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.13.1"
}
